"""add null to solution table

Revision ID: 55bb5cf48f9f
Revises: 65a25215005f
Create Date: 2025-10-22 11:37:31.419842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55bb5cf48f9f'
down_revision: Union[str, Sequence[str], None] = '65a25215005f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('label', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('label', 'solution',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
