"""create_tables

Revision ID: 65a25215005f
Revises: 2034d16129c8
Create Date: 2025-10-22 10:59:58.416078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '65a25215005f'
down_revision: Union[str, Sequence[str], None] = '2034d16129c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ready', 'progress', 'review', 'approve', name='imagestatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_assets_created_at'), 'image_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_assets_status'), 'image_assets', ['status'], unique=False)
    op.create_index('ix_image_assets_status_created', 'image_assets', ['status', 'created_at'], unique=False)
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solution', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_assets.id'], ),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_created_at'), 'annotations', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotations_created_at'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_table('label')
    op.drop_index('ix_image_assets_status_created', table_name='image_assets')
    op.drop_index(op.f('ix_image_assets_status'), table_name='image_assets')
    op.drop_index(op.f('ix_image_assets_created_at'), table_name='image_assets')
    op.drop_table('image_assets')
    # ### end Alembic commands ###
