"""fix boxes into box

Revision ID: fdaa7690fa81
Revises: be5ab9bc6d47
Create Date: 2025-10-22 14:34:44.294338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdaa7690fa81'
down_revision: Union[str, Sequence[str], None] = 'be5ab9bc6d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('bounding_box', sa.JSON(), nullable=True))
    op.drop_column('annotations', 'bounding_boxes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('bounding_boxes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('annotations', 'bounding_box')
    # ### end Alembic commands ###
